// Centralized mock data for the Real Estate Web3 application

export const assets = [
  {
    id: "1",
    title: "Downtown Luxury Apartments",
    category: "Real Estate",
    location: "New York, NY",
    image: "/luxury-apartment-building.png",
    price: "$2.5M",
    roi: "12.5%",
    investors: 234,
    totalShares: 1000,
    description: "Premium luxury apartments in the heart of downtown Manhattan with modern amenities.",
    nftData: {
      totalNFTs: 1000,
      nftPrice: "$2,500",
      nftSymbol: "DLA",
      royaltyPercentage: 12.5,
      floorPrice: "$2,400",
      holders: 234,
    },
    details: {
      yearBuilt: 2020,
      squareFeet: 250000,
      units: 85,
      occupancyRate: "98%",
      annualRevenue: "$3.2M",
    },
  },
  {
    id: "2",
    title: "Tech Hub Office Complex",
    category: "Commercial",
    location: "San Francisco, CA",
    image: "/modern-office-building.png",
    price: "$4.2M",
    roi: "15.3%",
    investors: 456,
    totalShares: 2000,
    description: "State-of-the-art office complex in the tech district with high occupancy rates.",
    nftData: {
      totalNFTs: 2000,
      nftPrice: "$2,100",
      nftSymbol: "THO",
      royaltyPercentage: 15.3,
      floorPrice: "$2,050",
      holders: 456,
    },
    details: {
      yearBuilt: 2019,
      squareFeet: 450000,
      floors: 12,
      occupancyRate: "96%",
      annualRevenue: "$5.1M",
    },
  },
  {
    id: "3",
    title: "Beachfront Resort",
    category: "Hospitality",
    location: "Miami, FL",
    image: "/beachfront-resort-hotel.jpg",
    price: "$3.8M",
    roi: "18.2%",
    investors: 189,
    totalShares: 1500,
    description: "Luxury beachfront resort with premium amenities and consistent revenue streams.",
    nftData: {
      totalNFTs: 1500,
      nftPrice: "$2,533",
      nftSymbol: "BFR",
      royaltyPercentage: 18.2,
      floorPrice: "$2,450",
      holders: 189,
    },
    details: {
      yearBuilt: 2018,
      squareFeet: 180000,
      rooms: 250,
      occupancyRate: "92%",
      annualRevenue: "$6.8M",
    },
  },
  {
    id: "4",
    title: "Shopping Mall Complex",
    category: "Retail",
    location: "Chicago, IL",
    image: "/shopping-mall-retail-center.jpg",
    price: "$5.1M",
    roi: "14.7%",
    investors: 312,
    totalShares: 2500,
    description: "Large-scale shopping mall with diverse retail tenants and strong foot traffic.",
    nftData: {
      totalNFTs: 2500,
      nftPrice: "$2,040",
      nftSymbol: "SMC",
      royaltyPercentage: 14.7,
      floorPrice: "$1,980",
      holders: 312,
    },
    details: {
      yearBuilt: 2015,
      squareFeet: 650000,
      stores: 180,
      occupancyRate: "94%",
      annualRevenue: "$7.5M",
    },
  },
  {
    id: "5",
    title: "Residential Tower",
    category: "Real Estate",
    location: "Los Angeles, CA",
    image: "/residential-apartment-tower.jpg",
    price: "$3.2M",
    roi: "11.9%",
    investors: 267,
    totalShares: 1200,
    description: "Modern residential tower with luxury units and excellent location.",
    nftData: {
      totalNFTs: 1200,
      nftPrice: "$2,667",
      nftSymbol: "RES",
      royaltyPercentage: 11.9,
      floorPrice: "$2,580",
      holders: 267,
    },
    details: {
      yearBuilt: 2021,
      squareFeet: 320000,
      units: 120,
      occupancyRate: "97%",
      annualRevenue: "$2.8M",
    },
  },
  {
    id: "6",
    title: "Industrial Warehouse",
    category: "Industrial",
    location: "Houston, TX",
    image: "/industrial-warehouse.png",
    price: "$1.8M",
    roi: "16.4%",
    investors: 145,
    totalShares: 800,
    description: "Strategic industrial warehouse with long-term lease agreements.",
    nftData: {
      totalNFTs: 800,
      nftPrice: "$2,250",
      nftSymbol: "IWH",
      royaltyPercentage: 16.4,
      floorPrice: "$2,180",
      holders: 145,
    },
    details: {
      yearBuilt: 2017,
      squareFeet: 500000,
      bays: 45,
      occupancyRate: "100%",
      annualRevenue: "$2.2M",
    },
  },
]

export const properties = assets

export const portfolioGrowthData = [
  { month: "Jan", value: 45000 },
  { month: "Feb", value: 52000 },
  { month: "Mar", value: 48000 },
  { month: "Apr", value: 61000 },
  { month: "May", value: 55000 },
  { month: "Jun", value: 67000 },
]

export const royaltyIncomeData = [
  { month: "Jan", amount: 1200 },
  { month: "Feb", amount: 1900 },
  { month: "Mar", amount: 1600 },
  { month: "Apr", amount: 2200 },
  { month: "May", amount: 2800 },
  { month: "Jun", amount: 3200 },
]

export const userInvestments = [
  {
    id: "1",
    property: "Downtown Luxury Apartments",
    shares: 100,
    value: "$25,000",
    roi: "12.5%",
    status: "Active",
  },
  {
    id: "2",
    property: "Tech Hub Office Complex",
    shares: 50,
    value: "$21,000",
    roi: "15.3%",
    status: "Active",
  },
  {
    id: "3",
    property: "Beachfront Resort",
    shares: 75,
    value: "$28,500",
    roi: "18.2%",
    status: "Active",
  },
]

export const userProperties = [
  {
    id: "1",
    title: "Downtown Luxury Apartments",
    location: "New York, NY",
    image: "/luxury-apartment-building.png",
    price: "$2.5M",
    roi: "12.5%",
    investors: 234,
  },
  {
    id: "2",
    title: "Tech Hub Office Complex",
    location: "San Francisco, CA",
    image: "/modern-office-building.png",
    price: "$4.2M",
    roi: "15.3%",
    investors: 456,
  },
]

export const royaltyPayouts = [
  {
    id: "1",
    property: "Downtown Luxury Apartments",
    amount: "$1,200",
    date: "Jun 1, 2024",
    status: "Paid",
  },
  {
    id: "2",
    property: "Tech Hub Office Complex",
    amount: "$1,500",
    date: "May 15, 2024",
    status: "Paid",
  },
  {
    id: "3",
    property: "Beachfront Resort",
    amount: "$1,100",
    date: "May 1, 2024",
    status: "Paid",
  },
  {
    id: "4",
    property: "Shopping Mall Complex",
    amount: "$800",
    date: "Apr 15, 2024",
    status: "Paid",
  },
]

export const dashboardStats = {
  portfolioValue: "$67,000",
  propertiesOwned: "8",
  totalROI: "14.8%",
  royaltyEarnings: "$3,200",
  totalInvested: "$74,500",
  currentValue: "$85,800",
  averageROI: "15.2%",
  totalEarned: "$12,000",
  pendingPayout: "$3,200",
  monthlyAverage: "$2,000",
  totalListedValue: "$6.7M",
  activeInvestors: "690",
  propertyAverageROI: "13.9%",
}
